routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/terms', function () {
    return view('terms');
});
Route::get('/', function () {
    return view('welcome');
});
Route::get('admin/login','Admin\UsersController@login')->name('show_login');
Route::post('admin/login','Admin\UsersController@doLogin')->name('do_login');
Route::get('admin/logout','Admin\UsersController@logout')->name('do_logout');
//Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // users route
    Route::resource('meals', 'MealsController');
    Route::resource('cities', 'CitiesController');
    Route::resource('regions', 'RegionsController');
    Route::resource('payNumbers', 'GenerateNumbersController');
    Route::resource('sports', 'SportsController');
    Route::resource('socials', 'SocialsController');
    Route::resource('chats', 'ChatsController');
    Route::get('chats/create/{user_id}', 'ChatsController@create');
    Route::resource('products', 'ProductsController');
    Route::resource('packages', 'PackagesController');
    Route::resource('carts', 'CartsController');
    Route::get('/orders/active/{id}','CartsController@active_order')->name('active_order');
    Route::get('/orders/refuse/{id}','CartsController@refuse_order')->name('refuse_order');
    Route::get('user/socials/{user_id}', 'UsersController@userSocials')->name('userSocials');
    Route::get('user/sports/{user_id}', 'SportsController@userSports')->name('userSports');
    Route::get('user/packages/{user_id}', 'PackagesController@userPackages')->name('packages');

    Route::get('package/active', 'PackagesController@activePackages')->name('active');

    Route::delete('package/destroy_package/{id}', 'PackagesController@destroy_package')->name('destroy_package');

    Route::post('package/active_package/{id}', 'PackagesController@active_package')->name('active_item');

    Route::post('package/un_active_package/{id}', 'PackagesController@un_active_package')->name('un_active_item');

    Route::get('package/un_active', 'PackagesController@unActivePackages')->name('un_active');
    // waters
    Route::get('users/waters', 'UsersController@waters')->name('users_waters');

    Route::get('user/carts/{user_id}', 'UsersController@userCarts')->name('userCarts');
    Route::resource('users', 'UsersController');
});

app/PayNumber.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PayNumber extends Model
{
    //
    protected $fillable = [
        'id',
        'generated_number',
        'price',
        'created_at'
    ];

}

resources/views/admin/payNumbers/create.blade.php
@extends('admin.layouts.home')
@section('title')
اضافة كروت شحن
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">اضافة كارت شحن </h5>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li><a data-action="reload"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body">
                    {!!Form::open( ['route' => 'payNumbers.store' ,
                    'class'=>'form phone_validate', 'method' => 'Post','files' => true]) !!}
                        @include('admin.PayNumbers.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
<!-- #END# Basic Validation -->
@endsection

@section('script')

    <script type="text/javascript" src="{{asset('admin/admin/assets/js/pages/form_layouts.js')}}"></script>
@endsection

resources/views/admin/payNumbers/edit.blade.php
@extends('admin.layouts.home')
@section('title')
تعديل كروت الشحن
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">تعديل كروت الشحن </h5>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li><a data-action="reload"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body">
                    {!!Form::model( $PayNumber,['route' => ['payNumbers.update' , $PayNumber->id],
                    'class'=>'form', 'method' => 'PATCH','files' => true]) !!}
                        @include('admin.PayNumbers.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
<!-- #END# Basic Validation -->
@endsection

@section('script')

    <script type="text/javascript" src="{{asset('admin/admin/assets/js/pages/form_layouts.js')}}"></script>
@endsection

resources/views/admin/payNumbers/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="form-group col-md-12 pull-left">
    <label>سعر كارت الشحن</label>
    {!! Form::text("price",(isset($payNumbers))?$payNumbers->price : null,['class'=>'form-control ','placeholder'=>'اكتب سعر كارت الشحن هنا'])!!}
</div>

<br>
<br>
<div class="text-center col-md-12">
    <div class="text-right">
        <button type="submit" class="btn btn-success">حفظ <i class="icon-arrow-left13 position-right"></i></button>
    </div>
</div>

resources/views/admin/payNumbers/index.blade.php
@extends('admin.layouts.home')
@section('title')
كروت الشحن
@endsection



@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">كل كروت الشحن  </h5>
            <div class="heading-elements">
                <ul class="icons-list">

                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
كل كروت الشحن         </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>رقم الكارت </th>
                <th>السعر </th>

                <th>العمليات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($PayNumbers as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->generated_number}}</td>
                    <td>{{$item->price}} ريال</td>
                    {!!Form::open( ['route' => ['payNumbers.destroy',$item->id] ,
                    'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                    <td>
                        <a href="{{route('payNumbers.edit',
                        ['id'=>$item->id])}}" data-toggle="tooltip"
                           data-original-title="تعديل">
                            <i class="icon-pencil7 text-inverse" style="margin-left: 10px"></i> </a>
                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip" data-original-title="حذف">
                            <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                    </td>

                </tr>
                <!-- Modal -->
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

    <div class="links">
        {{ $PayNumbers->links() }}
    </div>




    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف  ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف القسم تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }



    </script>

    <div class="row">
        <div id="container">
            <canvas id="canvas"></canvas>
        </div>

    </div>

@endsection