routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/terms', function () {
    return view('terms');
});
Route::get('/', function () {
    return view('welcome');
});
Route::get('admin/login','Admin\UsersController@login')->name('show_login');
Route::post('admin/login','Admin\UsersController@doLogin')->name('do_login');
Route::get('admin/logout','Admin\UsersController@logout')->name('do_logout');
//Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'middleware' => 'admin'], function()
{
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    // users route
    Route::resource('meals', 'MealsController');
    Route::resource('cities', 'CitiesController');
    Route::resource('regions', 'RegionsController');
    Route::resource('payNumbers', 'GenerateNumbersController');
    Route::resource('sports', 'SportsController');
    Route::resource('socials', 'SocialsController');
    Route::resource('chats', 'ChatsController');
    Route::get('chats/create/{user_id}', 'ChatsController@create');
    Route::resource('products', 'ProductsController');
    Route::resource('packages', 'PackagesController');
    Route::resource('carts', 'CartsController');
    Route::get('/orders/active/{id}','CartsController@active_order')->name('active_order');
    Route::get('/orders/refuse/{id}','CartsController@refuse_order')->name('refuse_order');
    Route::get('user/socials/{user_id}', 'UsersController@userSocials')->name('userSocials');
    Route::get('user/sports/{user_id}', 'SportsController@userSports')->name('userSports');
    Route::get('user/packages/{user_id}', 'PackagesController@userPackages')->name('packages');

    Route::get('package/active', 'PackagesController@activePackages')->name('active');

    Route::delete('package/destroy_package/{id}', 'PackagesController@destroy_package')->name('destroy_package');

    Route::post('package/active_package/{id}', 'PackagesController@active_package')->name('active_item');

    Route::post('package/un_active_package/{id}', 'PackagesController@un_active_package')->name('un_active_item');

    Route::get('package/un_active', 'PackagesController@unActivePackages')->name('un_active');
    // waters
    Route::get('users/waters', 'UsersController@waters')->name('users_waters');

    Route::get('user/carts/{user_id}', 'UsersController@userCarts')->name('userCarts');
    Route::resource('users', 'UsersController');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;

class User extends Authenticatable implements JWTSubject
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email','phone', 'password','image','active','active_message','city_id','region_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }
    public function getJWTCustomClaims()
    {
        return [];
    }


    public function socials(){
        return $this->hasMany('App\Social','user_id','id');
    }

    public function sports()
    {
        return $this->belongsToMany(Sport::class, 'today_sports');
    }

    public function Carts(){
        return $this->hasMany(Cart::class);
    }

    public function senderChats(){
        return $this->hasMany('App\Chat','sender','id');
    }

    public function receiverChats(){
        return $this->hasMany('App\Chat','receiver','id');
    }

    public function waters(){
        return $this->hasMany('App\Water','user_id','id');
    }

    public function city(){
        return $this->belongsTo('App\City','city_id','id');
    }

    public function region(){
        return $this->belongsTo('App\Regions','region_id','id');
    }

}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\CartProduct;
use App\Social;
use App\User;
use App\Water;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UsersController extends Controller
{
    //
    public function index(){
        $users = User::where('is_admin',null)->paginate(50);
         return view('admin.users.index')->with('users',$users);
    }

    public function login(){
        return view('admin.users.login');
    }
    public function doLogin(Request $request){
        $email = $request->get('email');
        $password = $request->get('password');

        // check is true user is admin
        if (Auth::attempt(['email' => $email, 'password' => $password]) && Auth::user()->is_admin == 1) {
            return view('admin.dashboard.index');
        }else{
            return redirect()->back()->with('error','you not admin');
        }
    }


    public function logout(Request $request) {
        Auth::logout();
        return redirect()->route('show_login');
    }

    public function create()
    {
        //
        return view('admin.users.create');


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //


        $validator = \Validator::make($request->all(),[
            'name'=>'required',
            'email'=>'required|email|unique:users',
            'address'=>'nullable',
            'weight'=>'nullable',
            'height'=>'nullable',
            'age'=>'nullable',
            'default_cals'=>'nullable',
            'default_water'=>'nullable',
            'type'=>'nullable',
            'fitness'=>'nullable',
            'phone'=>'required|unique:users',
            'password' => 'required|confirmed|min:6',
            'image'=>'required|mimes:jpeg,jpg,bmp,png|max:2048'
        ]);

        if ($validator->fails())
        {
            session()->flash('error','خطأ في البيانات');

            return back();
        }

        $user = new User();

        if ($request->has(['password']))
        {
            $user->password = Hash::make($request->password);
        }

        if ($request->has('image'))
        {
            $user->image = uploader($request->image);
        }

        $user->name = $request->name;
        $user->address = $request->address;
        $user->weight = $request->weight;
        $user->height = $request->height;
        $user->age = $request->age;
        $user->default_cals = $request->default_cals;
        $user->default_water = $request->default_water;
        $user->type = $request->type;
        $user->fitness = $request->fitness;
        $user->phone= $request->phone;
        $user->email = $request->email;
        $user->active_message = $request->active_message;
        $user->created_at = Carbon::now();



        if($user->save()){

            session()->flash('success','تم الحفظ  ');

        }

        return back();


    }

    public function edit($id)
    {


        $user = User::findOrFail($id);
        return view('admin.users.edit')
            ->with('user',$user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user =  User::findOrFail($id);


        //dd($request->all());
        $validator = \Validator::make($request->all(),[
            'name'=>'required',
            'address'=>'nullable',
            'weight'=>'nullable',
            'height'=>'nullable',
            'age'=>'nullable',
            'default_cals'=>'nullable',
            'default_water'=>'nullable',
            'type'=>'nullable',
            'fitness'=>'nullable',
            'email'=>'required|email|unique:users,email,'.$user->id,
            'phone'=>'required|unique:users,phone,'.$user->id,
        ]);


        if ($validator->fails())
        {
            session()->flash('error','خطأ في البيانات');

            return back();
        }


        if ($request->has('image'))
        {
            $validator = \Validator::make($request->all(),[
                'image'=>'required|mimes:jpeg,jpg,bmp,png|max:2048'
            ]);

            if ($validator->fails())
            {
                session()->flash('error','خطأ في الصورة');

                return back();
            }

            $user->image = uploader($request->image);
        }



        $user->name = $request->name;
        $user->address = $request->address;
        $user->weight = $request->weight;
        $user->height = $request->height;
        $user->age = $request->age;
        $user->default_cals = $request->default_cals;
        $user->default_water = $request->default_water;
        $user->type = $request->type;
        $user->fitness = $request->fitness;
        $user->phone= $request->phone;
        $user->email = $request->email;
        $user->active_message = $request->active_message;
        $user->updated_at = Carbon::now();

        if($user->save()){

            session()->flash('success','تم التعديل  ');

        }

        return back();
    }

    public function destroy($id)
    {
        $user = User::findOrFail($id);
        if($user->delete()){
            session()->flash('info','تم المسح  ');
            return redirect()->back();
        }
    }



    public function userCarts($user_id){



        $carts =  CartProduct::

            join('carts','carts.id','=','cart_product.cart_id')
            ->where('carts.user_id',$user_id)->paginate(50);

        return view('admin.users.carts')->with('carts',$carts);

    }


    public function userSocials($user_id){


        $socials =  Social::where('user_id',$user_id)->orderBy('created_at','DESC')->paginate(50);

        return view('admin.users.socials')->with('socials',$socials);

    }

    public function userSports($user_id){


        $socials =  Social::where('user_id',$user_id)->orderBy('created_at','DESC')->paginate(50);

        return view('admin.users.socials')->with('socials',$socials);

    }


    public function waters(){
        $waters = Water::paginate(50);

        return view('admin.users.waters')->with('waters',$waters);
    }


}

resources/views/admin/users/carts.blade.php
@extends('admin.layouts.home')
@section('title')
عربات المستخدم
@endsection

@section('content')


@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">كل المستخدم   </h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
كل العربات          </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>عنوان </th>
                <th>اسم المستخدم </th>
                <th>الكمية </th>
                <th>الحالة </th>
                <th>سعر الوجبة </th>
                <th>صورة الوجبة </th>
                <th>العمليات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($carts as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->product->title}}</td>
                    <td>{{$item->cart->user->name}}</td>
                    <td>{{$item->cart->quantity}}</td>
                    <td>
                        @if($item->cart->status == 'pending' )
                            {{'pending'}}
                        @elseif($item->cart->status == 'opening' )
                            {{' opening '}}
                        @elseif($item->cart->status == 'refused' )
                            {{' refused '}}
                        @endif
                    </td>
                    <td>{{$item->product->price}}</td>
                    <td><img src="{{getImg($item->product->image)}}" class="img-responsive" style="width: 200px; height: 200px"/> </td>



                    {!!Form::open( ['route' => ['carts.destroy',$item->id] ,
                    'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                    <td>
                        <a href="{{route('carts.edit',
                        ['id'=>$item->cart->id])}}" data-toggle="tooltip"
                           data-original-title="تعديل">
                            <i class="icon-pencil7 text-inverse" style="margin-left: 10px"></i> </a>
                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip" data-original-title="حذف">
                            <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                    </td>

                </tr>
                <!-- Modal -->
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

    <div class="links">
        {{ $carts->links() }}
    </div>




    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف  ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف القسم تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }



    </script>

    <div class="row">
        <div id="container">
            <canvas id="canvas"></canvas>
        </div>

    </div>

@endsection

resources/views/admin/users/create.blade.php
@extends('admin.layouts.home')
@section('title')
اضافة عضو جديد
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">اضافة عضو جديد</h5>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li><a data-action="reload"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body">
                    {!!Form::open( ['route' => 'users.store' ,
                    'class'=>'form phone_validate', 'method' => 'Post','files' => true]) !!}
                        @include('admin.users.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
<!-- #END# Basic Validation -->
@endsection

@section('script')

    <script type="text/javascript" src="{{asset('admin/admin/assets/js/pages/form_layouts.js')}}"></script>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.home')
@section('title')
اضافة عضو جديد
@endsection

@section('header')

@endsection

@section('content')
    <!-- Vertical form options -->
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-flat">
                <div class="panel-heading">
                    <h5 class="panel-title">اضافة عضو جديد</h5>
                    <div class="heading-elements">
                        <ul class="icons-list">
                            <li><a data-action="reload"></a></li>
                        </ul>
                    </div>
                </div>
                <div class="panel-body">
                    {!!Form::model($user, ['route' => ['users.update' , $user->id] ,
                    'class'=>'form phone_validate', 'method' => 'PATCH','files' => true]) !!}
                        @include('admin.users.form')
                    {!!Form::close() !!}
                </div>
            </div>
        </div>
    </div>
<!-- #END# Basic Validation -->
@endsection

@section('script')

    <script type="text/javascript" src="{{asset('admin/admin/assets/js/pages/form_layouts.js')}}"></script>
@endsection

resources/views/admin/users/form.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<div class="form-group col-md-12 pull-left">
    <label>الاسم </label>
    {!! Form::text("name",isset($user)? $user->name : null,['class'=>'form-control ','placeholder'=>'اكتب الاسم هنا'])!!}
</div>

<div class="form-group col-md-12 pull-left">
    <label>البريد الالكتورني </label>
    {!! Form::text("email",isset($user)? $user->email : null,['class'=>'form-control ','placeholder'=>'اكتب البريد الالكتروني هنا'])!!}
</div>

<div class="form-group col-md-12 pull-left">
    <label>العنوان </label>
    {!! Form::text("address",isset($user)? $user->address : null,['class'=>'form-control ','placeholder'=>'اكتب العنوان هنا'])!!}
</div>


<div class="form-group col-md-12 pull-left">
    <label>رقم الجوال </label>
    {!! Form::text("phone",isset($user)? $user->phone : null,['class'=>'form-control ','placeholder'=>'اكتب رقم الجوال هنا'])!!}
</div>

<div class="form-group col-md-12 pull-left">
    <label>الوزن </label>
    {!! Form::text("weight",isset($user)? $user->weight : null,['class'=>'form-control ','placeholder'=>'اكتب الوزن هنا'])!!}
</div>

<div class="form-group col-md-12 pull-left">
    <label>الطول </label>
    {!! Form::text("height",isset($user)? $user->height : null,['class'=>'form-control ','placeholder'=>'اكتب الطول هنا'])!!}
</div>

<div class="form-group col-md-12 pull-left">
    <label>العمر </label>
    {!! Form::text("age",isset($user)? $user->age : null,['class'=>'form-control ','placeholder'=>'اكتب العمر هنا'])!!}
</div>


<div class="form-group col-md-12 pull-left">
    <label>عدد الكالوري </label>
    {!! Form::text("default_cals",isset($user)? $user->default_cals : null,['class'=>'form-control ','placeholder'=>'اكتب عدد الكالوري هنا'])!!}
</div>

<div class="form-group col-md-12 pull-left">
    <label>عدد اكواب المياة</label>
    {!! Form::text("default_water",isset($user)? $user->default_water : null,['class'=>'form-control ','placeholder'=>'اكتب عدد اكواب المياة هنا'])!!}
</div>
<div class="form-group">
    <label>    النوع</label>
    {{ Form::select('type', [
        'male'  => 'ذكر',
        'female'  => 'انثي'
    ], isset($user)? $user->type : null,array('class'=>'form-control', 'placeholder'=>'اختار نوع هنا ')) }}
</div>


<div class="form-group">
    <label>    اللياقة</label>
    {{ Form::select('fitness', [
        'weak'  => 'ضعيف',
        'good'  => 'جيد',
        'very_good'  => 'جيد جدا',
    ],isset($user)? $user->fitness : null, array('class'=>'form-control', 'placeholder'=>'اختار اللياقة هنا ')) }}
</div>


<div class="form-group">
    <label>    تفعيل الشات للمستخدم</label>
    {{ Form::select('active_message', [
        '0'  => 'الغاء التقعيل',
        '1'  => 'تفعيل الشات',
    ],isset($user)? $user->active_message : null, array('class'=>'form-control', 'placeholder'=>'اختر حالة التفعيل هنا ')) }}
</div>
@if(!isset($user))
    <div class="form-group col-md-12 pull-left">
        <label>الرقم السري </label>
        {!! Form::input("password",'password',null,['class'=>'form-control ','placeholder'=>'اكتب الرقم السري هنا'])!!}
    </div>

    <div class="form-group col-md-12 pull-left">
        <label>اعد كتابه الرقم السري </label>
        {!! Form::input("password",'password_confirmation',null,['class'=>'form-control ',
        'placeholder'=>'اعد كتابه الرقم السري هنا'])!!}
    </div>
@endif
<div class="form-group col-md-12 pull-left">
    <label>صورة المستخدم </label>
    {!! Form::file("image",null,['class'=>'form-control ','required'])!!}
    <br>
    <br>
    <br>
    <div class="clearfix"></div>
    @if(isset($user))
        @if($user->image)
            <label> صورة القديمة  </label>
        <div class="clearfix"></div>

        <img src="{{getImg($user->image)}}"/>
        @endif
    @endif

</div>


<br>
<br>
<div class="text-center col-md-12">
    <div class="text-right">
        <button type="submit" class="btn btn-success">حفظ <i class="icon-arrow-left13 position-right"></i></button>
    </div>
</div>

resources/views/admin/users/index.blade.php
@extends('admin.layouts.home')
@section('title')
المستخدمين
@endsection

@section('content')


@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">كل العضويات</h5>
            <div class="heading-elements">
                <ul class="icons-list">

                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">



            <br>
            <br>
            عرض كل العضويات والتحكم بهم وبكل العمليات الخاصة بهم مع امكانية البحث وتصدير تقارير وملفات وطباعتهم
        </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>الاسم </th>
                <th>البريد</th>
                <th>الموبايل</th>
                <th>العمليات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->name}}</td>
                    <td>{{$item->email}}</td>
                    <td>{{$item->phone}}</td>
                    {!!Form::open( ['route' => ['users.destroy',$item->id] ,
                    'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                    <td>
                        <a href="{{route('userCarts',
                        ['id'=>$item->id])}}" data-toggle="tooltip"
                           data-original-title="عربات المستخدم ">
                            <i class="icon-cart text-inverse" style="margin-left: 10px"></i> </a>

                        <a href="{{route('userSports',
                        ['id'=>$item->id])}}" data-toggle="tooltip"
                           data-original-title="رياضات المستخدم ">
                            <i class="icon-file-spreadsheet text-inverse" style="margin-left: 10px"></i> </a>
                        <a href="{{route('userSocials',
                        ['id'=>$item->id])}}" data-toggle="tooltip"
                           data-original-title="وسائل التواصل ">
                            <i class="icon-image-compare text-inverse" style="margin-left: 10px"></i> </a>

                        <a href="{{route('users.edit',
                        ['id'=>$item->id])}}" data-toggle="tooltip"
                           data-original-title="تعديل">
                            <i class="icon-pencil7 text-inverse" style="margin-left: 10px"></i> </a>

                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip" data-original-title="حذف">
                            <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                    </td>

                </tr>
                <!-- Modal -->
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

    <div class="links">
        {{ $users->links() }}
    </div>




    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف هذا المستخدم ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف القسم تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }



    </script>

    <div class="row">
        <div id="container">
            <canvas id="canvas"></canvas>
        </div>

    </div>

@endsection

resources/views/admin/users/packages.blade.php
@extends('admin.layouts.home')
@section('title')
باقات المستخدم
@endsection

@section('content')


@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">باقات المستخدم</h5>
            <div class="heading-elements">
                <ul class="icons-list">

                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            باقات المستخدم         </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>الاسم </th>
                <th>عدد الوجبات </th>
                <th>السعر </th>
                <th>المدة </th>
                <th>التفاصيل </th>
                <th>العمليات</th>
            </tr>
            </thead>
            <tbody>
            @foreach($packages as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->package->title}}</td>
                    <td>{{$item->package->number_of_meal}}</td>
                    <td>{{$item->package->price}}</td>
                    <td>{{$item->package->expired_date}}</td>
                    <td>{{$item->package->details}}</td>
                    {!!Form::open( ['route' => ['packages.destroy',$item->id] ,
                    'id'=>'delete-form'.$item->id, 'method' => 'Delete']) !!}
                    {!!Form::close() !!}
                    <td>
                        <a href="{{route('packages.edit',
                        ['id'=>$item->id])}}" data-toggle="tooltip"
                           data-original-title="تعديل">
                            <i class="icon-pencil7 text-inverse" style="margin-left: 10px"></i> </a>
                        <a href="#" onclick="Delete({{$item->id}})" data-toggle="tooltip" data-original-title="حذف">
                            <i class="icon-trash text-inverse text-danger" style="margin-left: 10px"></i> </a>
                    </td>

                </tr>
                <!-- Modal -->
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

    <div class="links">
        {{ $packages->links() }}
    </div>




    <script>
        function Delete(id) {
            var item_id=id;
            console.log(item_id);
            swal({
                title: "هل أنت متأكد ",
                text: "هل تريد حذف  ؟",
                icon: "warning",
                buttons: ["الغاء", "موافق"],
                dangerMode: true,

            }).then(function(isConfirm){
                if(isConfirm){
                    document.getElementById('delete-form'+item_id).submit();
                }
                else{
                    swal("تم االإلفاء", "حذف القسم تم الغاؤه",'info',{buttons:'موافق'});
                }
            });
        }



    </script>

    <div class="row">
        <div id="container">
            <canvas id="canvas"></canvas>
        </div>

    </div>

@endsection

resources/views/admin/users/socials.blade.php
@extends('admin.layouts.home')
@section('title')
    وسائل التواصل للمستخدم
@endsection

@section('content')


@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title">    وسائل التواصل للمستخدم </h5>
            <div class="heading-elements">
                <ul class="icons-list">
                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            وسائل التواصل للمستخدم </div>
        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>الاسم </th>
                <th>الصورة </th>
                <th>likes </th>
                <th>loves </th>
            </tr>
            </thead>
            <tbody>
            @foreach($socials as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->user->name}}</td>
                    <td><img src="{{getImg($item->data)}}" class="img-responsive" style="width: 200px; height: 200px"/> </td>
                    <td>{{$item->likes}}</td>
                    <td>{{$item->loves}}</td>
                    <td></td>
                </tr>
                <!-- Modal -->
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

    <div class="links">
        {{ $socials->links() }}
    </div>





    <div class="row">
        <div id="container">
            <canvas id="canvas"></canvas>
        </div>

    </div>

@endsection

resources/views/admin/users/sports.blade.php
@extends('admin.layouts.home')
@section('title')
الرياضيات
@endsection

@section('content')


@section('content')

    <!-- Basic initialization -->
    <div class="panel panel-flat">
        <div class="panel-heading">
            <h5 class="panel-title"> رياضيات المستخدم  </h5>
            <div class="heading-elements">
                <ul class="icons-list">

                    <li><a data-action="reload"></a></li>
                </ul>
            </div>
        </div>

        <div class="panel-body">
            رياضيات المستخدم </div>

        <table class="table datatable-button-init-basic">
            <thead>
            <tr>
                <th> # </th>
                <th>الاسم </th>
                <th>الوقت </th>
                <th>الوقت المستنفذ</th>
                <th>عدد الكالوي </th>
                <th>الصورة </th>

            </tr>
            </thead>
            <tbody>
            @foreach($sports as $key=>$item)
                <tr>
                    <td>{{$key+1}}</td>
                    <td>{{$item->sport->title}}</td>
                    <td>{{$item->sport->default_sport_time}}</td>
                    <td>{{$item->spend_time}}</td>
                    <td>{{$item->sport->cals}}</td>
                    <td><img src="{{getImg($item->sport->image)}}" class="img-responsive" style="width: 200px; height: 200px"/> </td>
                </tr>
                <!-- Modal -->
            @endforeach
            </tbody>
        </table>
    </div>
    <!-- /basic initialization -->

    <div class="links">
        {{ $sports->links() }}
    </div>

    <div class="row">
        <div id="container">
            <canvas id="canvas"></canvas>
        </div>

    </div>

@endsection